### ISSUE TITLE
コマンドラインからGroupが作成できない

### ISSUE THREAD

**Issue by j3tm0t0** [soracom/soracom-sdk-ruby#1]
http://qiita.com/domokun70cm/items/7b1b43f6b9321e66a73b

```
[ec2-user@ip-172-31-20-195 ~]$ soracom group create
/usr/local/share/ruby/gems/2.0/gems/soracom-1.0.1/lib/soracom/client.rb:204:in `create_group': wrong number of arguments (2 for 0) (ArgumentError)
    from /usr/local/share/ruby/gems/2.0/gems/soracom-1.0.1/lib/soracom/cli.rb:141:in `create'
    from /usr/local/share/ruby/gems/2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /usr/local/share/ruby/gems/2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /usr/local/share/ruby/gems/2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /usr/local/share/ruby/gems/2.0/gems/thor-0.19.1/lib/thor/invocation.rb:115:in `invoke'
    from /usr/local/share/ruby/gems/2.0/gems/thor-0.19.1/lib/thor.rb:235:in `block in subcommand'
    from /usr/local/share/ruby/gems/2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /usr/local/share/ruby/gems/2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /usr/local/share/ruby/gems/2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /usr/local/share/ruby/gems/2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /usr/local/share/ruby/gems/2.0/gems/soracom-1.0.1/exe/soracom:5:in `<top (required)>'
    from /usr/local/bin/soracom:23:in `load'
    from /usr/local/bin/soracom:23:in `<main>'
```

**Comment by j3tm0t0** [comment]
done
